### ISSUE TITLE
Have you considered creating a Patreon account?

### ISSUE THREAD

**Issue by ChojinDSL** [gamer-os/gamer-os.github.io#3]
Hi, this is a really great project. But from what I can tell, you're mostly working on this all by yourself. Have you considered setting up a patreon account or something similar, so that people can support this project even if they can't code? Donations would be totally voluntary of course.

**Comment by alkazar** [comment]
I briefly thought about it, but I wouldn't have anything to offer as rewards or goals. I wouldn't expect many people to become patrons so it doesn't seem worth the effort either. Maybe at some point in the future.
