### ISSUE TITLE
Swap recommendation of Etcher in favor of anything that doesn’t phone home

### ISSUE THREAD

**Issue by fitojb** [gamer-os/gamer-os.github.io#4]

**Comment by ghost** [comment]
Like UNetBootin?

**Comment by fitojb** [comment]
Yes, but also maybe https://gitlab.com/bztsrc/usbimager which has a friendlier UI.

**Comment by ghost** [comment]
Ah. I’ve never heard of that.

**Comment by ghost** [comment]
> Yes, but also maybe https://gitlab.com/bztsrc/usbimager which has a friendlier UI.

The only thing that may be a learning curve for some is the fact that (as far as I know) it needs to be built from source, but that’s easy. Just `make` and then `sudo make install` in the src folder

**Comment by alkazar** [comment]
Etcher is easy to use and cross platform which is why it was selected.

**Comment by fitojb** [comment]
@alkazar It seems you completely missed the part about phoning home.

**Comment by alkazar** [comment]
@fitojb What exact behaviour of etcher do you object to? The ads?

**Comment by fitojb** [comment]
@alkazar No, I object to the phoning home (the forced telemetry and other unannounced connections visible with tools like Wireshark)
